/* XAML control ABI declarations. Derived from the Microsoft Windows SDK
 * interface definitions published in windows-rs 0.36.1. */
enum node_interface { NODE_IDependencyObject, NODE_IUIElement, NODE_IFrameworkElement, NODE_IControl, NODE_IPage, NODE_IUserControl, NODE_IContentControl, NODE_IPanel, NODE_ICanvas, NODE_ISwapChainPanel, NODE_ITextBox, NODE_ITextBox2, NODE_IButton, NODE_ISolidColorBrush, NODE_IFontFamily, NODE_IBrush, NODE_IFACE_COUNT };
static const GUID node_iid_IDependencyObject = {0x5c526665,0xf60e,0x4912,{0xaf,0x59,0x5f,0xe0,0x68,0x0f,0x08,0x9d}};
struct node_IDependencyObject_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *GetValue)(struct node_iface *iface, IInspectable * dp, IInspectable ** result__);
    HRESULT (WINAPI *SetValue)(struct node_iface *iface, IInspectable * dp, IInspectable * value);
    HRESULT (WINAPI *ClearValue)(struct node_iface *iface, IInspectable * dp);
    HRESULT (WINAPI *ReadLocalValue)(struct node_iface *iface, IInspectable * dp, IInspectable ** result__);
    HRESULT (WINAPI *GetAnimationBaseValue)(struct node_iface *iface, IInspectable * dp, IInspectable ** result__);
    HRESULT (WINAPI *Dispatcher)(struct node_iface *iface, IInspectable ** result__);
};
static const GUID node_iid_IUIElement = {0x676d0be9,0xb65c,0x41c6,{0xba,0x40,0x58,0xcf,0x87,0xf2,0x01,0xc1}};
struct node_IUIElement_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *DesiredSize)(struct node_iface *iface, Size * result__);
    HRESULT (WINAPI *AllowDrop)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetAllowDrop)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *Opacity)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetOpacity)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *Clip)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetClip)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *RenderTransform)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetRenderTransform)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *Projection)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetProjection)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *RenderTransformOrigin)(struct node_iface *iface, Point * result__);
    HRESULT (WINAPI *SetRenderTransformOrigin)(struct node_iface *iface, Point value);
    HRESULT (WINAPI *IsHitTestVisible)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsHitTestVisible)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *Visibility)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetVisibility)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *RenderSize)(struct node_iface *iface, Size * result__);
    HRESULT (WINAPI *UseLayoutRounding)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetUseLayoutRounding)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *Transitions)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetTransitions)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *CacheMode)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetCacheMode)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *IsTapEnabled)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsTapEnabled)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *IsDoubleTapEnabled)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsDoubleTapEnabled)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *IsRightTapEnabled)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsRightTapEnabled)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *IsHoldingEnabled)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsHoldingEnabled)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *ManipulationMode)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetManipulationMode)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *PointerCaptures)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *KeyUp)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveKeyUp)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *KeyDown)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveKeyDown)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *GotFocus)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveGotFocus)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *LostFocus)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveLostFocus)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *DragEnter)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveDragEnter)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *DragLeave)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveDragLeave)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *DragOver)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveDragOver)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *Drop)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveDrop)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *PointerPressed)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePointerPressed)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *PointerMoved)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePointerMoved)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *PointerReleased)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePointerReleased)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *PointerEntered)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePointerEntered)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *PointerExited)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePointerExited)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *PointerCaptureLost)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePointerCaptureLost)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *PointerCanceled)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePointerCanceled)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *PointerWheelChanged)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePointerWheelChanged)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *Tapped)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveTapped)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *DoubleTapped)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveDoubleTapped)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *Holding)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveHolding)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *RightTapped)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveRightTapped)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *ManipulationStarting)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveManipulationStarting)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *ManipulationInertiaStarting)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveManipulationInertiaStarting)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *ManipulationStarted)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveManipulationStarted)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *ManipulationDelta)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveManipulationDelta)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *ManipulationCompleted)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveManipulationCompleted)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *Measure)(struct node_iface *iface, Size availablesize);
    HRESULT (WINAPI *Arrange)(struct node_iface *iface, Rect finalrect);
    HRESULT (WINAPI *CapturePointer)(struct node_iface *iface, IInspectable * value, boolean * result__);
    HRESULT (WINAPI *ReleasePointerCapture)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *ReleasePointerCaptures)(struct node_iface *iface);
    HRESULT (WINAPI *AddHandler)(struct node_iface *iface, IInspectable * routedevent, IInspectable * handler, boolean handledeventstoo);
    HRESULT (WINAPI *RemoveHandler)(struct node_iface *iface, IInspectable * routedevent, IInspectable * handler);
    HRESULT (WINAPI *TransformToVisual)(struct node_iface *iface, IInspectable * visual, IInspectable ** result__);
    HRESULT (WINAPI *InvalidateMeasure)(struct node_iface *iface);
    HRESULT (WINAPI *InvalidateArrange)(struct node_iface *iface);
    HRESULT (WINAPI *UpdateLayout)(struct node_iface *iface);
};
static const GUID node_iid_IFrameworkElement = {0xa391d09b,0x4a99,0x4b7c,{0x9d,0x8d,0x6f,0xa5,0xd0,0x1f,0x6f,0xbf}};
struct node_IFrameworkElement_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Triggers)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *Resources)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetResources)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *Tag)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetTag)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *Language)(struct node_iface *iface, HSTRING * result__);
    HRESULT (WINAPI *SetLanguage)(struct node_iface *iface, HSTRING value);
    HRESULT (WINAPI *ActualWidth)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *ActualHeight)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *Width)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetWidth)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *Height)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetHeight)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *MinWidth)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetMinWidth)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *MaxWidth)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetMaxWidth)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *MinHeight)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetMinHeight)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *MaxHeight)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetMaxHeight)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *HorizontalAlignment)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetHorizontalAlignment)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *VerticalAlignment)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetVerticalAlignment)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *Margin)(struct node_iface *iface, struct node_thickness * result__);
    HRESULT (WINAPI *SetMargin)(struct node_iface *iface, struct node_thickness value);
    HRESULT (WINAPI *Name)(struct node_iface *iface, HSTRING * result__);
    HRESULT (WINAPI *SetName)(struct node_iface *iface, HSTRING value);
    HRESULT (WINAPI *BaseUri)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *DataContext)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetDataContext)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *Style)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetStyle)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *Parent)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *FlowDirection)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetFlowDirection)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *Loaded)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveLoaded)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *Unloaded)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveUnloaded)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *SizeChanged)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveSizeChanged)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *LayoutUpdated)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveLayoutUpdated)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *FindName)(struct node_iface *iface, HSTRING name, IInspectable ** result__);
    HRESULT (WINAPI *SetBinding)(struct node_iface *iface, IInspectable * dp, IInspectable * binding);
};
static const GUID node_iid_IControl = {0xa8912263,0x2951,0x4f58,{0xa9,0xc5,0x5a,0x13,0x4e,0xaa,0x7f,0x07}};
struct node_IControl_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *FontSize)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetFontSize)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *FontFamily)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetFontFamily)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *FontWeight)(struct node_iface *iface, struct node_weight * result__);
    HRESULT (WINAPI *SetFontWeight)(struct node_iface *iface, struct node_weight value);
    HRESULT (WINAPI *FontStyle)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetFontStyle)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *FontStretch)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetFontStretch)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *CharacterSpacing)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetCharacterSpacing)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *Foreground)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetForeground)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *IsTabStop)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsTabStop)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *IsEnabled)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsEnabled)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *TabIndex)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetTabIndex)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *TabNavigation)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetTabNavigation)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *Template)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetTemplate)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *Padding)(struct node_iface *iface, struct node_thickness * result__);
    HRESULT (WINAPI *SetPadding)(struct node_iface *iface, struct node_thickness value);
    HRESULT (WINAPI *HorizontalContentAlignment)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetHorizontalContentAlignment)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *VerticalContentAlignment)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetVerticalContentAlignment)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *Background)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetBackground)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *BorderThickness)(struct node_iface *iface, struct node_thickness * result__);
    HRESULT (WINAPI *SetBorderThickness)(struct node_iface *iface, struct node_thickness value);
    HRESULT (WINAPI *BorderBrush)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetBorderBrush)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *FocusState)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *IsEnabledChanged)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveIsEnabledChanged)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *ApplyTemplate)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *Focus)(struct node_iface *iface, INT32 value, boolean * result__);
};
static const GUID node_iid_IPage = {0xc4b27075,0xe641,0x453e,{0x82,0x4d,0x01,0x2f,0xc7,0xcf,0x95,0xcf}};
struct node_IPage_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Frame)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *NavigationCacheMode)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetNavigationCacheMode)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *TopAppBar)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetTopAppBar)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *BottomAppBar)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetBottomAppBar)(struct node_iface *iface, IInspectable * value);
};
static const GUID node_iid_IUserControl = {0xa7a69ec9,0xea35,0x4679,{0xbf,0x29,0xf4,0xf0,0x92,0x86,0xd3,0x14}};
struct node_IUserControl_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Content)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetContent)(struct node_iface *iface, IInspectable * value);
};
static const GUID node_iid_IContentControl = {0xa26dd1dc,0xcd44,0x435c,{0xbe,0x94,0x01,0xd6,0x24,0x1c,0x23,0x1c}};
struct node_IContentControl_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Content)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetContent)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *ContentTemplate)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetContentTemplate)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *ContentTemplateSelector)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetContentTemplateSelector)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *ContentTransitions)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetContentTransitions)(struct node_iface *iface, IInspectable * value);
};
static const GUID node_iid_IPanel = {0xa50a4bbd,0x8361,0x469c,{0x90,0xda,0xe9,0xa4,0x0c,0x74,0x74,0xdf}};
struct node_IPanel_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Children)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *Background)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetBackground)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *IsItemsHost)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *ChildrenTransitions)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetChildrenTransitions)(struct node_iface *iface, IInspectable * value);
};
static const GUID node_iid_ICanvas = {0x79190e19,0xcd38,0x4823,{0xae,0xae,0x64,0xa7,0x71,0x32,0xf5,0x19}};
struct node_ICanvas_vtbl {
    struct node_base_vtbl base;
};
static const GUID node_iid_ISwapChainPanel = {0xc589644f,0xeba8,0x427a,{0xb7,0x5a,0x9f,0x1f,0x93,0xa1,0x1a,0xe9}};
struct node_ISwapChainPanel_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *CompositionScaleX)(struct node_iface *iface, FLOAT * result__);
    HRESULT (WINAPI *CompositionScaleY)(struct node_iface *iface, FLOAT * result__);
    HRESULT (WINAPI *CompositionScaleChanged)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveCompositionScaleChanged)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *CreateCoreIndependentInputSource)(struct node_iface *iface, INT32 devicetypes, IInspectable ** result__);
};
static const GUID node_iid_ITextBox = {0xe48f5a8b,0x1dff,0x4352,{0xa1,0xf4,0xe5,0x16,0x51,0x4e,0xc8,0x82}};
struct node_ITextBox_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Text)(struct node_iface *iface, HSTRING * result__);
    HRESULT (WINAPI *SetText)(struct node_iface *iface, HSTRING value);
    HRESULT (WINAPI *SelectedText)(struct node_iface *iface, HSTRING * result__);
    HRESULT (WINAPI *SetSelectedText)(struct node_iface *iface, HSTRING value);
    HRESULT (WINAPI *SelectionLength)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetSelectionLength)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *SelectionStart)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetSelectionStart)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *MaxLength)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetMaxLength)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *IsReadOnly)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsReadOnly)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *AcceptsReturn)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetAcceptsReturn)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *TextAlignment)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetTextAlignment)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *TextWrapping)(struct node_iface *iface, INT32 * result__);
    HRESULT (WINAPI *SetTextWrapping)(struct node_iface *iface, INT32 value);
    HRESULT (WINAPI *IsSpellCheckEnabled)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsSpellCheckEnabled)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *IsTextPredictionEnabled)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsTextPredictionEnabled)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *InputScope)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetInputScope)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *TextChanged)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveTextChanged)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *SelectionChanged)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveSelectionChanged)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *ContextMenuOpening)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemoveContextMenuOpening)(struct node_iface *iface, EventRegistrationToken token);
    HRESULT (WINAPI *Select)(struct node_iface *iface, INT32 start, INT32 length);
    HRESULT (WINAPI *SelectAll)(struct node_iface *iface);
    HRESULT (WINAPI *GetRectFromCharacterIndex)(struct node_iface *iface, INT32 charindex, boolean trailingedge, Rect * result__);
};
static const GUID node_iid_ITextBox2 = {0xf7168c00,0x1432,0x462a,{0x94,0x05,0x38,0xf3,0x85,0xbf,0xc3,0x7c}};
struct node_ITextBox2_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Header)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetHeader)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *HeaderTemplate)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetHeaderTemplate)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *PlaceholderText)(struct node_iface *iface, HSTRING * result__);
    HRESULT (WINAPI *SetPlaceholderText)(struct node_iface *iface, HSTRING value);
    HRESULT (WINAPI *SelectionHighlightColor)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetSelectionHighlightColor)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *PreventKeyboardDisplayOnProgrammaticFocus)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetPreventKeyboardDisplayOnProgrammaticFocus)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *IsColorFontEnabled)(struct node_iface *iface, boolean * result__);
    HRESULT (WINAPI *SetIsColorFontEnabled)(struct node_iface *iface, boolean value);
    HRESULT (WINAPI *Paste)(struct node_iface *iface, IInspectable * handler, EventRegistrationToken * result__);
    HRESULT (WINAPI *RemovePaste)(struct node_iface *iface, EventRegistrationToken token);
};
static const GUID node_iid_IButton = {0x280335ae,0x5570,0x46c7,{0x8e,0x0b,0x60,0x2b,0xe7,0x12,0x29,0xa2}};
struct node_IButton_vtbl {
    struct node_base_vtbl base;
};
static const GUID node_iid_ISolidColorBrush = {0x9d850850,0x66f3,0x48df,{0x9a,0x8f,0x82,0x4b,0xd5,0xe0,0x70,0xaf}};
struct node_ISolidColorBrush_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Color)(struct node_iface *iface, Color * result__);
    HRESULT (WINAPI *SetColor)(struct node_iface *iface, Color value);
};
static const GUID node_iid_IFontFamily = {0x92467e64,0xd66a,0x4cf4,{0x93,0x22,0x3d,0x23,0xb3,0xc0,0xc3,0x61}};
struct node_IFontFamily_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Source)(struct node_iface *iface, HSTRING * result__);
};
static const GUID node_iid_IBrush = {0x8806a321,0x1e06,0x422c,{0xa1,0xcc,0x01,0x69,0x65,0x59,0xe0,0x21}};
struct node_IBrush_vtbl {
    struct node_base_vtbl base;
    HRESULT (WINAPI *Opacity)(struct node_iface *iface, DOUBLE * result__);
    HRESULT (WINAPI *SetOpacity)(struct node_iface *iface, DOUBLE value);
    HRESULT (WINAPI *Transform)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetTransform)(struct node_iface *iface, IInspectable * value);
    HRESULT (WINAPI *RelativeTransform)(struct node_iface *iface, IInspectable ** result__);
    HRESULT (WINAPI *SetRelativeTransform)(struct node_iface *iface, IInspectable * value);
};
static const GUID *const node_iids[] = {&node_iid_IDependencyObject, &node_iid_IUIElement, &node_iid_IFrameworkElement, &node_iid_IControl, &node_iid_IPage, &node_iid_IUserControl, &node_iid_IContentControl, &node_iid_IPanel, &node_iid_ICanvas, &node_iid_ISwapChainPanel, &node_iid_ITextBox, &node_iid_ITextBox2, &node_iid_IButton, &node_iid_ISolidColorBrush, &node_iid_IFontFamily, &node_iid_IBrush};
