/*
 * Copyright 2022 Rémi Bernon for CodeWeavers
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifdef __WIDL__
#pragma winrt ns_prefix
#endif

import "inspectable.idl";
import "windows.foundation.idl";

namespace Windows.System.Power {
    typedef enum BatteryStatus BatteryStatus;

    [contract(Windows.Foundation.UniversalApiContract, 1.0)]
    enum BatteryStatus
    {
        NotPresent = 0,
        Discharging = 1,
        Idle = 2,
        Charging = 3,
    };
}

namespace Windows.System.Power {
    typedef enum EnergySaverStatus EnergySaverStatus;
    typedef enum PowerSupplyStatus PowerSupplyStatus;
    runtimeclass PowerManager;
    [contract(Windows.Foundation.UniversalApiContract, 1.0)]
    enum EnergySaverStatus { Disabled = 0, Off = 1, On = 2 };
    [contract(Windows.Foundation.UniversalApiContract, 1.0)]
    enum PowerSupplyStatus { NotPresent = 0, Inadequate = 1, Adequate = 2 };
    [contract(Windows.Foundation.UniversalApiContract, 1.0), exclusiveto(Windows.System.Power.PowerManager),
     uuid(1394825d-62ce-4364-98d5-aa28c7fbd15b)]
    interface IPowerManagerStatics : IInspectable
    {
        [propget] HRESULT EnergySaverStatus([out, retval] EnergySaverStatus *value);
        [eventadd] HRESULT EnergySaverStatusChanged([in] Windows.Foundation.EventHandler<IInspectable *> *handler, [out, retval] EventRegistrationToken *token);
        [eventremove] HRESULT EnergySaverStatusChanged([in] EventRegistrationToken token);
        [propget] HRESULT BatteryStatus([out, retval] BatteryStatus *value);
        [eventadd] HRESULT BatteryStatusChanged([in] Windows.Foundation.EventHandler<IInspectable *> *handler, [out, retval] EventRegistrationToken *token);
        [eventremove] HRESULT BatteryStatusChanged([in] EventRegistrationToken token);
        [propget] HRESULT PowerSupplyStatus([out, retval] PowerSupplyStatus *value);
        [eventadd] HRESULT PowerSupplyStatusChanged([in] Windows.Foundation.EventHandler<IInspectable *> *handler, [out, retval] EventRegistrationToken *token);
        [eventremove] HRESULT PowerSupplyStatusChanged([in] EventRegistrationToken token);
        [propget] HRESULT RemainingChargePercent([out, retval] INT32 *value);
        [eventadd] HRESULT RemainingChargePercentChanged([in] Windows.Foundation.EventHandler<IInspectable *> *handler, [out, retval] EventRegistrationToken *token);
        [eventremove] HRESULT RemainingChargePercentChanged([in] EventRegistrationToken token);
        [propget] HRESULT RemainingDischargeTime([out, retval] Windows.Foundation.TimeSpan *value);
        [eventadd] HRESULT RemainingDischargeTimeChanged([in] Windows.Foundation.EventHandler<IInspectable *> *handler, [out, retval] EventRegistrationToken *token);
        [eventremove] HRESULT RemainingDischargeTimeChanged([in] EventRegistrationToken token);
    }
    [contract(Windows.Foundation.UniversalApiContract, 1.0),
     static(Windows.System.Power.IPowerManagerStatics, Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass PowerManager { }
}
