/* UWP file picker contracts. SPDX-License-Identifier: LGPL-2.1-or-later */
#ifdef __WIDL__
#pragma winrt ns_prefix
#endif
import "windows.storage.idl";
namespace Windows.Storage.Pickers {
    typedef enum PickerLocationId PickerLocationId;
    typedef enum PickerViewMode PickerViewMode;
    [contract(Windows.Foundation.UniversalApiContract,1.0)]
    enum PickerLocationId { DocumentsLibrary=0, ComputerFolder=1, Desktop=2, Downloads=3,
        HomeGroup=4, MusicLibrary=5, PicturesLibrary=6, VideosLibrary=7, Objects3D=8, Unspecified=9 };
    [contract(Windows.Foundation.UniversalApiContract,1.0)]
    enum PickerViewMode { List=0, Thumbnail=1 };
    declare {
        interface Windows.Foundation.Collections.IIterator<Windows.Storage.StorageFile *>;
        interface Windows.Foundation.Collections.IIterable<Windows.Storage.StorageFile *>;
        interface Windows.Foundation.Collections.IVector<Windows.Storage.StorageFile *>;
    }
    declare {
        interface Windows.Foundation.Collections.IVector<HSTRING>;
        interface Windows.Foundation.Collections.IKeyValuePair<HSTRING, Windows.Foundation.Collections.IVector<HSTRING> *>;
        interface Windows.Foundation.Collections.IIterator<Windows.Foundation.Collections.IKeyValuePair<HSTRING, Windows.Foundation.Collections.IVector<HSTRING> *> *>;
        interface Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<HSTRING, Windows.Foundation.Collections.IVector<HSTRING> *> *>;
        interface Windows.Foundation.Collections.IMapView<HSTRING, Windows.Foundation.Collections.IVector<HSTRING> *>;
        interface Windows.Foundation.Collections.IMap<HSTRING, Windows.Foundation.Collections.IVector<HSTRING> *>;
    }
    runtimeclass FileSavePicker;
    [uuid(3286ffcb-617f-4cc5-af6a-b3fdf29ad145),exclusiveto(FileSavePicker)]
    interface IFileSavePicker : IInspectable {
        [propget] HRESULT SettingsIdentifier([out,retval] HSTRING *value);
        [propput] HRESULT SettingsIdentifier([in] HSTRING value);
        [propget] HRESULT SuggestedStartLocation([out,retval] Windows.Storage.Pickers.PickerLocationId *value);
        [propput] HRESULT SuggestedStartLocation([in] Windows.Storage.Pickers.PickerLocationId value);
        [propget] HRESULT CommitButtonText([out,retval] HSTRING *value);
        [propput] HRESULT CommitButtonText([in] HSTRING value);
        [propget] HRESULT FileTypeChoices([out,retval] Windows.Foundation.Collections.IMap<HSTRING, Windows.Foundation.Collections.IVector<HSTRING> *> **value);
        [propget] HRESULT DefaultFileExtension([out,retval] HSTRING *value);
        [propput] HRESULT DefaultFileExtension([in] HSTRING value);
        [propget] HRESULT SuggestedSaveFile([out,retval] Windows.Storage.StorageFile **value);
        [propput] HRESULT SuggestedSaveFile([in] Windows.Storage.StorageFile *value);
        [propget] HRESULT SuggestedFileName([out,retval] HSTRING *value);
        [propput] HRESULT SuggestedFileName([in] HSTRING value);
        HRESULT PickSaveFileAsync([out,retval] Windows.Foundation.IAsyncOperation<Windows.Storage.StorageFile *> **operation);
    }
    [contract(Windows.Foundation.UniversalApiContract,1.0),activatable(Windows.Foundation.UniversalApiContract,1.0)]
    runtimeclass FileSavePicker { [default] interface IFileSavePicker; }
    runtimeclass FileOpenPicker;
    [uuid(2ca8278a-12c5-4c5f-8977-94547793c241),exclusiveto(FileOpenPicker)]
    interface IFileOpenPicker : IInspectable {
        [propget] HRESULT ViewMode([out,retval] Windows.Storage.Pickers.PickerViewMode *value);
        [propput] HRESULT ViewMode([in] Windows.Storage.Pickers.PickerViewMode value);
        [propget] HRESULT SettingsIdentifier([out,retval] HSTRING *value);
        [propput] HRESULT SettingsIdentifier([in] HSTRING value);
        [propget] HRESULT SuggestedStartLocation([out,retval] Windows.Storage.Pickers.PickerLocationId *value);
        [propput] HRESULT SuggestedStartLocation([in] Windows.Storage.Pickers.PickerLocationId value);
        [propget] HRESULT CommitButtonText([out,retval] HSTRING *value);
        [propput] HRESULT CommitButtonText([in] HSTRING value);
        [propget] HRESULT FileTypeFilter([out,retval] Windows.Foundation.Collections.IVector<HSTRING> **value);
        HRESULT PickSingleFileAsync([out,retval] Windows.Foundation.IAsyncOperation<Windows.Storage.StorageFile *> **operation);
        HRESULT PickMultipleFilesAsync([out,retval] Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Storage.StorageFile *> *> **operation);
    }
    [contract(Windows.Foundation.UniversalApiContract,1.0),activatable(Windows.Foundation.UniversalApiContract,1.0)]
    runtimeclass FileOpenPicker { [default] interface IFileOpenPicker; }
}
