/*
 * Copyright (C) 2022 Mohamad Al-Jaf
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifdef __WIDL__
#pragma winrt ns_prefix
#endif

import "inspectable.idl";
import "asyncinfo.idl";
import "eventtoken.idl";
import "windowscontracts.idl";
import "windows.foundation.idl";
import "windows.security.cryptography.core.idl";
import "windows.storage.streams.idl";
import "windows.system.idl";

namespace Windows.Security.Cryptography.Core {
    typedef enum CryptographicPublicKeyBlobType CryptographicPublicKeyBlobType;
}

namespace Windows.Security.Credentials {
    runtimeclass PasswordCredential;

    [uuid(6ab18989-c720-41a7-a6c1-feadb36329a0), exclusiveto(Windows.Security.Credentials.PasswordCredential), contract(Windows.Foundation.UniversalApiContract, 1.0)]
    interface IPasswordCredential : IInspectable
    {
        [propget] HRESULT Resource([out, retval] HSTRING *value);
        [propput] HRESULT Resource([in] HSTRING value);
        [propget] HRESULT UserName([out, retval] HSTRING *value);
        [propput] HRESULT UserName([in] HSTRING value);
        [propget] HRESULT Password([out, retval] HSTRING *value);
        [propput] HRESULT Password([in] HSTRING value);
        HRESULT RetrievePassword();
        [propget] HRESULT Properties([out, retval] Windows.Foundation.Collections.IPropertySet **value);
    }

    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile)]
    runtimeclass PasswordCredential { [default] interface Windows.Security.Credentials.IPasswordCredential; }

    typedef enum KeyCredentialAttestationStatus KeyCredentialAttestationStatus;
    typedef enum KeyCredentialCreationOption KeyCredentialCreationOption;
    typedef enum KeyCredentialStatus KeyCredentialStatus;

    interface IKeyCredential;
    interface IKeyCredentialAttestationResult;
    interface IKeyCredentialManagerStatics;
    interface IKeyCredentialOperationResult;
    interface IKeyCredentialRetrievalResult;

    runtimeclass KeyCredential;
    runtimeclass KeyCredentialAttestationResult;
    runtimeclass KeyCredentialManager;
    runtimeclass KeyCredentialOperationResult;
    runtimeclass KeyCredentialRetrievalResult;

    declare {
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Credentials.KeyCredentialAttestationResult *>;
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Credentials.KeyCredentialOperationResult *>;
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Credentials.KeyCredentialRetrievalResult *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.KeyCredentialAttestationResult *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.KeyCredentialOperationResult *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.KeyCredentialRetrievalResult *>;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0)
    ]
    enum KeyCredentialAttestationStatus
    {
        Success          = 0,
        UnknownError     = 1,
        NotSupported     = 2,
        TemporaryFailure = 3,
    };

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0)
    ]
    enum KeyCredentialCreationOption
    {
        ReplaceExisting = 0,
        FailIfExists    = 1,
    };

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0)
    ]
    enum KeyCredentialStatus
    {
        Success                 = 0,
        UnknownError            = 1,
        NotFound                = 2,
        UserCanceled            = 3,
        UserPrefersPassword     = 4,
        CredentialAlreadyExists = 5,
        SecurityDeviceLocked    = 6,
    };

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Credentials.KeyCredential),
        uuid(9585ef8d-457b-4847-b11a-fa960bbdb138)
    ]
    interface IKeyCredential : IInspectable
    {
        [propget] HRESULT Name([out, retval] HSTRING *value);
        [overload("RetrievePublicKey")] HRESULT RetrievePublicKeyWithDefaultBlobType([out, retval] Windows.Storage.Streams.IBuffer **value);
        [overload("RetrievePublicKey")] HRESULT RetrievePublicKeyWithBlobType([in] Windows.Security.Cryptography.Core.CryptographicPublicKeyBlobType blobType, [out, retval] Windows.Storage.Streams.IBuffer **value);
        HRESULT RequestSignAsync([in] Windows.Storage.Streams.IBuffer *data, [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.KeyCredentialOperationResult *> **value);
        HRESULT GetAttestationAsync([out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.KeyCredentialAttestationResult *> **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Credentials.KeyCredentialAttestationResult),
        uuid(78aab3a1-a3c1-4103-b6cc-472c44171cbb)
    ]
    interface IKeyCredentialAttestationResult : IInspectable
    {
        [propget] HRESULT CertificateChainBuffer([out, retval] Windows.Storage.Streams.IBuffer **value);
        [propget] HRESULT AttestationBuffer([out, retval] Windows.Storage.Streams.IBuffer **value);
        [propget] HRESULT Status([out, retval] Windows.Security.Credentials.KeyCredentialAttestationStatus *value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Credentials.KeyCredentialManager),
        uuid(6aac468b-0ef1-4ce0-8290-4106da6a63b5)
    ]
    interface IKeyCredentialManagerStatics : IInspectable
    {
        HRESULT IsSupportedAsync([out, retval] Windows.Foundation.IAsyncOperation<boolean> **value);
        HRESULT RenewAttestationAsync([out, retval] Windows.Foundation.IAsyncAction **operation);
        HRESULT RequestCreateAsync(HSTRING name, Windows.Security.Credentials.KeyCredentialCreationOption option,
                                   [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.KeyCredentialRetrievalResult *> **value);
        HRESULT OpenAsync(HSTRING name, [out, retval] Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.KeyCredentialRetrievalResult *> **value);
        HRESULT DeleteAsync(HSTRING name, [out, retval] Windows.Foundation.IAsyncAction **operation);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Credentials.KeyCredentialOperationResult),
        uuid(f53786c1-5261-4cdd-976d-cc909ac71620)
    ]
    interface IKeyCredentialOperationResult : IInspectable
    {
        [propget] HRESULT Result([out, retval] Windows.Storage.Streams.IBuffer **value);
        [propget] HRESULT Status([out, retval] Windows.Security.Credentials.KeyCredentialStatus *value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Security.Credentials.KeyCredentialRetrievalResult),
        uuid(58cd7703-8d87-4249-9b58-f6598cc9644e)
    ]
    interface IKeyCredentialRetrievalResult : IInspectable
    {
        [propget] HRESULT Credential([out, retval] Windows.Security.Credentials.KeyCredential **value);
        [propget] HRESULT Status([out, retval] Windows.Security.Credentials.KeyCredentialStatus *value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass KeyCredential
    {
        [default] interface Windows.Security.Credentials.IKeyCredential;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass KeyCredentialAttestationResult
    {
        [default] interface Windows.Security.Credentials.IKeyCredentialAttestationResult;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        static(Windows.Security.Credentials.IKeyCredentialManagerStatics, Windows.Foundation.UniversalApiContract, 1.0),
        threading(both)
    ]
    runtimeclass KeyCredentialManager
    {
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass KeyCredentialOperationResult
    {
        [default] interface Windows.Security.Credentials.IKeyCredentialOperationResult;
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile)
    ]
    runtimeclass KeyCredentialRetrievalResult
    {
        [default] interface Windows.Security.Credentials.IKeyCredentialRetrievalResult;
    }
}

namespace Windows.Security.Credentials {
    typedef enum WebAccountState WebAccountState;
    typedef enum WebAccountPictureSize WebAccountPictureSize;
    runtimeclass WebAccountProvider;
    runtimeclass WebAccount;
    [contract(Windows.Foundation.UniversalApiContract,1.0)] enum WebAccountState { None=0, Connected=1, Error=2 };
    [contract(Windows.Foundation.UniversalApiContract,1.0)] enum WebAccountPictureSize { Size64x64=64, Size208x208=208, Size424x424=424, Size1080x1080=1080 };
    [uuid(29dcc8c3-7ab9-4a7c-a336-b942f9dbf7c7), exclusiveto(WebAccountProvider)]
    interface IWebAccountProvider : IInspectable {
        [propget] HRESULT Id([out,retval] HSTRING *value);
        [propget] HRESULT DisplayName([out,retval] HSTRING *value);
        [propget] HRESULT IconUri([out,retval] Windows.Foundation.Uri **value);
    }
    [uuid(4a01eb05-4e42-41d4-b518-e008a5163614), exclusiveto(WebAccountProvider)]
    interface IWebAccountProvider2 : IInspectable {
        [propget] HRESULT DisplayPurpose([out,retval] HSTRING *value);
        [propget] HRESULT Authority([out,retval] HSTRING *value);
    }
    [uuid(69473eb2-8031-49be-80bb-96cb46d99aba), exclusiveto(WebAccount)]
    interface IWebAccount : IInspectable {
        [propget] HRESULT WebAccountProvider([out,retval] WebAccountProvider **value);
        [propget] HRESULT UserName([out,retval] HSTRING *value);
        [propget] HRESULT State([out,retval] WebAccountState *value);
    }
    [uuid(7b56d6f8-990b-4eb5-94a7-5621f3a8b824), exclusiveto(WebAccount)]
    interface IWebAccount2 : IInspectable {
        [propget] HRESULT Id([out,retval] HSTRING *value);
        [propget] HRESULT Properties([out,retval] Windows.Foundation.Collections.IMapView<HSTRING,HSTRING> **value);
        HRESULT GetPictureAsync([in] WebAccountPictureSize size,[out,retval] Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IRandomAccessStream *> **value);
        HRESULT SignOutAsync([out,retval] Windows.Foundation.IAsyncAction **value);
        HRESULT SignOutWithClientIdAsync([in] HSTRING client,[out,retval] Windows.Foundation.IAsyncAction **value);
    }
    [contract(Windows.Foundation.UniversalApiContract,1.0)] runtimeclass WebAccountProvider { [default] interface IWebAccountProvider; interface IWebAccountProvider2; }
    [contract(Windows.Foundation.UniversalApiContract,1.0)] runtimeclass WebAccount { [default] interface IWebAccount; interface IWebAccount2; }
    declare {
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Credentials.WebAccountProvider *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccountProvider *>;
        interface Windows.Foundation.AsyncOperationCompletedHandler<Windows.Security.Credentials.WebAccount *>;
        interface Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.WebAccount *>;
    }
}
