/*
 * Copyright 2025 Vibhav Pant
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#ifdef __WIDL__
#pragma winrt ns_prefix
#endif

import "windowscontracts.idl";
import "windows.foundation.idl";
import "windows.networking.idl";
import "windows.security.credentials.idl";
import "windows.storage.streams.idl";

namespace Windows.Networking.Sockets {
    typedef enum SocketProtectionLevel SocketProtectionLevel;

    [contract(Windows.Foundation.UniversalApiContract, 1.0)]
    enum SocketProtectionLevel
    {
        PlainSocket = 0,
        Ssl = 1,
        SslAllowNullEncryption = 2,
        [contract(Windows.Foundation.UniversalApiContract, 1.0)]
        BluetoothEncryptionAllowNullAuthentication = 3,
        [contract(Windows.Foundation.UniversalApiContract, 1.0)]
        BluetoothEncryptionWithAuthentication = 4,
        [contract(Windows.Foundation.UniversalApiContract, 1.0)]
        Ssl3AllowWeakEncryption = 5,
        [contract(Windows.Foundation.UniversalApiContract, 1.0)]
        Tls10 = 6,
        [contract(Windows.Foundation.UniversalApiContract, 1.0)]
        Tls11 = 7,
        [contract(Windows.Foundation.UniversalApiContract, 1.0)]
        Tls12 = 8,
        [contract(Windows.Foundation.UniversalApiContract, 5.0)]
        Unspecified = 9,
        [contract(Windows.Foundation.UniversalApiContract, 16.0)]
        Tls13 = 10,
    };
}

namespace Windows.Networking.Sockets {
    typedef enum SocketMessageType SocketMessageType;
    typedef struct BandwidthStatistics BandwidthStatistics;
    [contract(Windows.Foundation.UniversalApiContract, 1.0)]
    enum SocketMessageType { Binary = 0, Utf8 = 1 };
    [contract(Windows.Foundation.UniversalApiContract, 1.0)]
    struct BandwidthStatistics
    {
        UINT64 OutboundBitsPerSecond;
        UINT64 InboundBitsPerSecond;
        UINT64 OutboundBitsPerSecondInstability;
        UINT64 InboundBitsPerSecondInstability;
        boolean OutboundBandwidthPeaked;
        boolean InboundBandwidthPeaked;
    };
    interface IMessageWebSocket;
    interface IMessageWebSocketControl;
    interface IWebSocket;
    interface IWebSocketInformation;
    runtimeclass MessageWebSocket;
    runtimeclass MessageWebSocketControl;
    runtimeclass MessageWebSocketInformation;
    runtimeclass MessageWebSocketMessageReceivedEventArgs;
    runtimeclass WebSocketClosedEventArgs;

    declare {
        interface Windows.Foundation.TypedEventHandler<Windows.Networking.Sockets.MessageWebSocket *, Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs *>;
        interface Windows.Foundation.TypedEventHandler<Windows.Networking.Sockets.IWebSocket *, Windows.Networking.Sockets.WebSocketClosedEventArgs *>;
    }

    [uuid(33727d08-34d5-4746-ad7b-8dde5bc2ef88), exclusiveto(Windows.Networking.Sockets.MessageWebSocket), contract(Windows.Foundation.UniversalApiContract, 1.0)]
    interface IMessageWebSocket : IInspectable
        requires Windows.Networking.Sockets.IWebSocket, Windows.Foundation.IClosable
    {
        [propget] HRESULT Control([out, retval] Windows.Networking.Sockets.MessageWebSocketControl **value);
        [propget] HRESULT Information([out, retval] Windows.Networking.Sockets.MessageWebSocketInformation **value);
        [eventadd] HRESULT MessageReceived([in] Windows.Foundation.TypedEventHandler<Windows.Networking.Sockets.MessageWebSocket *, Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs *> *handler, [out, retval] EventRegistrationToken *token);
        [eventremove] HRESULT MessageReceived([in] EventRegistrationToken token);
    }

    [uuid(f877396f-99b1-4e18-bc08-850c9adf156e), contract(Windows.Foundation.UniversalApiContract, 1.0)]
    interface IWebSocket : IInspectable requires Windows.Foundation.IClosable
    {
        [propget] HRESULT OutputStream([out, retval] Windows.Storage.Streams.IOutputStream **value);
        HRESULT ConnectAsync([in] Windows.Foundation.Uri *uri, [out, retval] Windows.Foundation.IAsyncAction **action);
        HRESULT SetRequestHeader([in] HSTRING name, [in] HSTRING value);
        [eventadd] HRESULT Closed([in] Windows.Foundation.TypedEventHandler<Windows.Networking.Sockets.IWebSocket *, Windows.Networking.Sockets.WebSocketClosedEventArgs *> *handler, [out, retval] EventRegistrationToken *token);
        [eventremove] HRESULT Closed([in] EventRegistrationToken token);
        HRESULT Close([in] UINT16 code, [in] HSTRING reason);
    }

    [uuid(8118388a-c629-4f0a-80fb-81fc05538862), exclusiveto(Windows.Networking.Sockets.MessageWebSocketControl), contract(Windows.Foundation.UniversalApiContract, 1.0)]
    interface IMessageWebSocketControl : IInspectable
    {
        [propget] HRESULT MaxMessageSize([out, retval] UINT32 *value);
        [propput] HRESULT MaxMessageSize([in] UINT32 value);
        [propget] HRESULT MessageType([out, retval] Windows.Networking.Sockets.SocketMessageType *value);
        [propput] HRESULT MessageType([in] Windows.Networking.Sockets.SocketMessageType value);
    }

    [uuid(2ec4bdc3-d9a5-455a-9811-de24d45337e9), contract(Windows.Foundation.UniversalApiContract, 1.0)]
    interface IWebSocketControl : IInspectable
    {
        [propget] HRESULT OutboundBufferSizeInBytes([out, retval] UINT32 *value);
        [propput] HRESULT OutboundBufferSizeInBytes([in] UINT32 value);
        [propget] HRESULT ServerCredential([out, retval] Windows.Security.Credentials.PasswordCredential **value);
        [propput] HRESULT ServerCredential([in] Windows.Security.Credentials.PasswordCredential *value);
        [propget] HRESULT ProxyCredential([out, retval] Windows.Security.Credentials.PasswordCredential **value);
        [propput] HRESULT ProxyCredential([in] Windows.Security.Credentials.PasswordCredential *value);
        [propget] HRESULT SupportedProtocols([out, retval] Windows.Foundation.Collections.IVector<HSTRING> **value);
    }

    [uuid(5e01e316-c92a-47a5-b25f-07847639d181), contract(Windows.Foundation.UniversalApiContract, 1.0)]
    interface IWebSocketInformation : IInspectable
    {
        [propget] HRESULT LocalAddress([out, retval] Windows.Networking.HostName **value);
        [propget] HRESULT BandwidthStatistics([out, retval] Windows.Networking.Sockets.BandwidthStatistics *value);
        [propget] HRESULT Protocol([out, retval] HSTRING *value);
    }

    [uuid(478c22ac-4c4b-42ed-9ed7-1ef9f94fa3d5), exclusiveto(Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs), contract(Windows.Foundation.UniversalApiContract, 1.0)]
    interface IMessageWebSocketMessageReceivedEventArgs : IInspectable
    {
        [propget] HRESULT MessageType([out, retval] Windows.Networking.Sockets.SocketMessageType *value);
        HRESULT GetDataReader([out, retval] Windows.Storage.Streams.DataReader **value);
        HRESULT GetDataStream([out, retval] Windows.Storage.Streams.IInputStream **value);
    }

    [uuid(ceb78d07-d0a8-4703-a091-c8c2c0915bc3), exclusiveto(Windows.Networking.Sockets.WebSocketClosedEventArgs), contract(Windows.Foundation.UniversalApiContract, 1.0)]
    interface IWebSocketClosedEventArgs : IInspectable
    {
        [propget] HRESULT Code([out, retval] UINT16 *value);
        [propget] HRESULT Reason([out, retval] HSTRING *value);
    }

    [activatable(Windows.Foundation.UniversalApiContract, 1.0), contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile), threading(both)]
    runtimeclass MessageWebSocket
    {
        [default] interface Windows.Networking.Sockets.IMessageWebSocket;
        interface Windows.Networking.Sockets.IWebSocket;
        interface Windows.Foundation.IClosable;
    }
    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile)]
    runtimeclass MessageWebSocketControl
    {
        [default] interface Windows.Networking.Sockets.IMessageWebSocketControl;
        interface Windows.Networking.Sockets.IWebSocketControl;
    }
    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile)]
    runtimeclass MessageWebSocketInformation { [default] interface Windows.Networking.Sockets.IWebSocketInformation; }
    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile)]
    runtimeclass MessageWebSocketMessageReceivedEventArgs { [default] interface Windows.Networking.Sockets.IMessageWebSocketMessageReceivedEventArgs; }
    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile)]
    runtimeclass WebSocketClosedEventArgs { [default] interface Windows.Networking.Sockets.IWebSocketClosedEventArgs; }
}
